spring:
  sql:
    init:
      mode: always
  application:
    name: teste-guarani
  datasource:
    url: jdbc:mysql://localhost:3306/loja_online?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

jwt:
  public:
    key: classpath:public.key
  private:
    key: classpath:private.key

logging:
  level:
    org.springframework.security: DEBUG

